# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"

  Inst_N=2 

  config.vm.define "server" do |serv|
    serv.vm.provider :"virtualbox" do |virt|
      virt.name = "zabbix-Server"
      virt.memory = "2048"
    end
    serv.vm.hostname = "zabbix.epam.com"
    serv.vm.network "private_network", ip: "192.168.1.250"
    serv.vm.provision "shell", inline: <<-SHELL
      echo "192.168.1.100  puppet.epam.com" >> /etc/hosts
      echo "192.168.1.250  zabbix.epam.com" >> /etc/hosts
      yum install puppet
      puppet agent --test
    SHELL
  end
  
  Inst_N.times do |i|
    config.vm.define "agent#{i+1}" do |agent|
    	agent.vm.provider :"virtualbox" do |virt|
      	   virt.name = "zabbix_agent_#{i+1}"
      	   virt.memory = "1024"
        end
      agent.vm.hostname = "agent#{i+1}.epam.com"
      agent.vm.network "private_network", ip: "192.168.1.20#{i+1}"
      agent.vm.provision "shell", inline: <<-SHELL
        echo "192.168.1.100  puppet.epam.com" >> /etc/hosts
        yum install puppet
        puppet agent --test --server 192.168.1.250
      SHELL

    end
  end

end
